// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/prospects": {
    params: {};
  };
  "/prospects/:id": {
    params: {
      "id": string;
    };
  };
  "/import": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/api/extension/dashboard": {
    params: {};
  };
  "/api/extension/connection-status": {
    params: {};
  };
  "/api/extension/prospect": {
    params: {};
  };
  "/batch": {
    params: {};
  };
  "/twitter": {
    params: {};
  };
  "/search": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/prospects" | "/prospects/:id" | "/import" | "/discover" | "/api/extension/dashboard" | "/api/extension/connection-status" | "/api/extension/prospect" | "/batch" | "/twitter" | "/search";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/prospects" | "/prospects/:id" | "/import" | "/discover";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/prospects._index.tsx": {
    id: "routes/prospects._index";
    page: "/prospects";
  };
  "routes/prospect.$id.tsx": {
    id: "routes/prospect.$id";
    page: "/prospects/:id";
  };
  "routes/import.tsx": {
    id: "routes/import";
    page: "/import";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/api.extension.dashboard.ts": {
    id: "routes/api.extension.dashboard";
    page: "/api/extension/dashboard";
  };
  "routes/api.extension.connection-status.ts": {
    id: "routes/api.extension.connection-status";
    page: "/api/extension/connection-status";
  };
  "routes/api.extension.prospect.ts": {
    id: "routes/api.extension.prospect";
    page: "/api/extension/prospect";
  };
  "routes/_redirects/batch.ts": {
    id: "routes/_redirects/batch";
    page: "/batch";
  };
  "routes/_redirects/twitter.ts": {
    id: "routes/_redirects/twitter";
    page: "/twitter";
  };
  "routes/_redirects/search.ts": {
    id: "routes/_redirects/search";
    page: "/search";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_app": typeof import("./app/routes/_app.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/prospects._index": typeof import("./app/routes/prospects._index.tsx");
  "routes/prospect.$id": typeof import("./app/routes/prospect.$id.tsx");
  "routes/import": typeof import("./app/routes/import.tsx");
  "routes/discover": typeof import("./app/routes/discover.tsx");
  "routes/api.extension.dashboard": typeof import("./app/routes/api.extension.dashboard.ts");
  "routes/api.extension.connection-status": typeof import("./app/routes/api.extension.connection-status.ts");
  "routes/api.extension.prospect": typeof import("./app/routes/api.extension.prospect.ts");
  "routes/_redirects/batch": typeof import("./app/routes/_redirects/batch.ts");
  "routes/_redirects/twitter": typeof import("./app/routes/_redirects/twitter.ts");
  "routes/_redirects/search": typeof import("./app/routes/_redirects/search.ts");
};