// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/batch": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/batch";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/batch.tsx": {
    id: "routes/batch";
    page: "/batch";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/batch": typeof import("./app/routes/batch.tsx");
};