// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/batch": {
    params: {};
  };
  "/twitter": {
    params: {};
  };
  "/discover": {
    params: {};
  };
  "/search": {
    params: {};
  };
  "/api/extension/dashboard": {
    params: {};
  };
  "/api/extension/connection-status": {
    params: {};
  };
  "/api/extension/prospect": {
    params: {};
  };
  "/prospects/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/batch" | "/twitter" | "/discover" | "/search" | "/api/extension/dashboard" | "/api/extension/connection-status" | "/api/extension/prospect" | "/prospects/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/batch.tsx": {
    id: "routes/batch";
    page: "/batch";
  };
  "routes/twitter.tsx": {
    id: "routes/twitter";
    page: "/twitter";
  };
  "routes/discover.tsx": {
    id: "routes/discover";
    page: "/discover";
  };
  "routes/search.tsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/api.extension.dashboard.ts": {
    id: "routes/api.extension.dashboard";
    page: "/api/extension/dashboard";
  };
  "routes/api.extension.connection-status.ts": {
    id: "routes/api.extension.connection-status";
    page: "/api/extension/connection-status";
  };
  "routes/api.extension.prospect.ts": {
    id: "routes/api.extension.prospect";
    page: "/api/extension/prospect";
  };
  "routes/prospect.$id.tsx": {
    id: "routes/prospect.$id";
    page: "/prospects/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/batch": typeof import("./app/routes/batch.tsx");
  "routes/twitter": typeof import("./app/routes/twitter.tsx");
  "routes/discover": typeof import("./app/routes/discover.tsx");
  "routes/search": typeof import("./app/routes/search.tsx");
  "routes/api.extension.dashboard": typeof import("./app/routes/api.extension.dashboard.ts");
  "routes/api.extension.connection-status": typeof import("./app/routes/api.extension.connection-status.ts");
  "routes/api.extension.prospect": typeof import("./app/routes/api.extension.prospect.ts");
  "routes/prospect.$id": typeof import("./app/routes/prospect.$id.tsx");
};